name: Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Set env
      run: |
        python3 -m venv env
        ln -s env/bin/activate
        . activate
    - name: Install dependencies
      env:
        CHIA_MACHINE_SSH_KEY: ${{ secrets.CHIA_MACHINE_SSH_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${CHIA_MACHINE_SSH_KEY}"
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt 
    - name: Test with pytest
      run: |
        py.test tests
